FROM maven:latest AS build

COPY . .

RUN --mount=type=cache,target=/root/.m2 mvn clean package -DskipTests

FROM openjdk:17

RUN mkdir /media/stories
RUN mkdir /media/feeds
RUN mkdir /media/feeds/avatars
RUN mkdir /media/feeds/images

COPY --from=build target/*.jar /app.jar

CMD ["java", "-jar", "app.jar"]