version: "3.5"

services:

  spring-dev:
    container_name: spring-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - maven_dev_dependencies:/root/.m2
      - ./media:/media
    command:
      sh -c "sleep 10 && java -Dspring.profiles.active=dev -jar app.jar"
    ports:
      - "8080:8080"

  mongo-dev:
    container_name: mongodb-dev
    image: mongo
    restart: always
    env_file:
      - dev.env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express-dev:
    container_name: mongo-express-dev
    image: mongo-express
    restart: always
    env_file:
      - dev.env
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}

  nginx-dev:
    container_name: dev-server
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    command: ["sh", "-c", "sleep 20 && nginx -g 'daemon off;'"]
    volumes:
      - ./media:/media
    ports:
      - "5173:5173"

volumes:
  maven_dev_dependencies:
  mongodb_dev_data:
