version: "3.5"

services:

  spring:
    container_name: spring
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      sh -c "sleep 10 && java -jar app.jar"
    ports:
      - "8080:8080"

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}

  nginx:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./nginx
    command: ["sh", "-c", "sleep 20 && nginx -g 'daemon off;'"]
    volumes:
      - ./media:/media
    ports:
      - "5173:5173"

volumes:
  mongodb_data:
