version: "3.5"

services:

  spring-test:
    container_name: tests
    build:
      context: ./
      dockerfile: Dockerfile.test
    volumes:
      - maven-volumes:/root/.m2
    command:
      sh -c "sleep 10 && mvn -Dspring.profiles.active=test test"
    ports:
      - "8080:8080"

  mongo-test:
    container_name: test-mongodb
    image: mongo
    restart: always
    env_file:
      - test.env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  maven-volumes: